### PR TITLE
chore(package): Update inquirer 0.11.0 -> 5.2.0

### PR DESCRIPTION
**Pull request by jhermsmeier**
Change-Type: major

### CODE REVIEW

**Review by pimterry — COMMENTED** [review]
Code looks fine ofc, but we're going to need to update the CI config too (currently all the tests fail because they use Node < 4).

How have you tested this doesn't break anything? The automated tests look like they stub out inquirer entirely, so just getting them passing won't tell you very much.

**Comment by jhermsmeier** [comment]
> How have you tested this doesn't break anything? The automated tests look like they stub out inquirer entirely, so just getting them passing won't tell you very much.

I created some test examples, which I've PRd as https://github.com/resin-io-modules/resin-cli-form/pull/21 now – turns out I forgot to rebuild the coffeescript though, and inquirer@5 doesn't quite work with this as it is.

**Comment by jhermsmeier** [comment]
> Code looks fine ofc, but we're going to need to update the CI config too (currently all the tests fail because they use Node < 4).

Updated in https://github.com/resin-io-modules/resin-cli-form/pull/22

**Comment by jhermsmeier** [comment]
Rebased against master with #22 included now

**Comment by jhermsmeier** [comment]
Obsoleted by https://github.com/resin-io-modules/resin-cli-form/pull/24

**Pull request closed without merging**
