### PR TITLE
feat(example): Add runnable examples

### PR DESCRIPTION
**Pull request by jhermsmeier**
This adds local runnable examples

Change-Type: patch

### CODE REVIEW

**Review by pimterry — APPROVED** [review]
Code LGTM, but we'll need to wait for #22 before we can merge.

**Comment by jhermsmeier** [comment]
Rebased against master with #22 included now

**Comment by pimterry** [comment]
@jhermsmeier both this and #20 still seem to have the appveyor tests failing with drivelist errors for some reason.

**Comment by jhermsmeier** [comment]
@pimterry yeah, the drivelist prebuilds for Windows are failing due to a Node 10 issue which we still need to fix

**Review by Page- — APPROVED** [review]

**Review by pimterry — APPROVED** [review]

**Pull request merged**
