### PR TITLE
chore(test): Update Node versions on CI

### PR DESCRIPTION
**Pull request by jhermsmeier**
This updates Node versions used on CI from (0.10.x, 0.11.x, 0.12.x) to (6.x.x, 8.x.x, 10.x.x)

Change-Type: patch

### CODE REVIEW

**Review by pimterry — COMMENTED** [review]
This fails to build in Appveyor because drivelist isn't prebuilt for Node v10 (though Travis manages to build it from scratch successfully).

We should definitely fix that asap, since it'll cause more problems like this elsewhere - I've filed a PR: https://github.com/resin-io-modules/drivelist/pull/273

**Comment by pimterry** [comment]
@jhermsmeier looks like this is now failing because of some new deprecations in Node 10: `Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead`.

Not really clear exactly where that's coming from, any idea?

**Comment by jhermsmeier** [comment]
@pimterry yes, this is from gulp-mocha:

```
[20:10:37] DeprecationWarning in plugin 'gulp-mocha'
Message:
    Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
Details:
    code: DEP0097
    domain: [object Object]
    domainThrown: true
Stack:
DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
  at emitMakeCallbackDeprecation (domain.js:106:13)
  at process.topLevelDomainCallback (domain.js:117:5)
```

We need to update `gulp-mocha`, and `mocha` to get rid of this warning

**Comment by jhermsmeier** [comment]
@pimterry fixed the test situation

**Review by pimterry — APPROVED** [review]

**Pull request merged**
